# 项目相关配置
dataapi-boot:
  # 名称
  name: dataapi-boot
  # 版本
  version: 2.0.0
  # 版权年份
  copyrightYear: 2021
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8084
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    # Tomcat启动初始化的线程数，默认值25
    threads:
      max: 800
      min-spare: 30



spring:
  application:
    name: dataapi-boot
  profiles:
    active: development
  #支持名称相同的bean的覆盖
  main:
    allow-bean-definition-overriding: true
#  data:
#    mongodb:
#      uri: mongodb://iot:iot@125.46.16.2:50035
#      database: iotdata
  #      host: 125.46.16.2
#      port: 50035
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true