apiVersion: v1
kind: Service
metadata:
  name: datacenter-service
  namespace: xidianiot
  labels:
    app: datacenter-service
spec:
  type: NodePort
  ports:
  - name: datacenter-api
    port: 9999
    targetPort: 9999
    nodePort: 30009
  selector:
    app: datacenter